import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // sans.className: Open_Sans font 지정
    <html lang="en" className={sans.className}>
      {/* w-full 너비 꽉 채우지만 max-w-screen-2xl 까지만으로 제한(1536px) */}
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto">
        <Header />
        {/* grow: 위아래 꽉 채우기 */}
        <main className="grow bg-sky-400">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
